### PR TITLE
docs: adding a modest README

### PR DESCRIPTION
**Pull request by davidjoy**
Gives a warning, gives a little background, gives a few links.

### CODE REVIEW

**Review by sarina — APPROVED** [review]

**Comment by sarina** [comment]
Any suggestions for what I should add to the "About" section on the homepage of the repo?

image

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @davidjoy! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
@davidjoy 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-base&entry.867055334=https://github.com/openedx/frontend-base/pull/2&entry.1484655318=https://github.com/davidjoy&entry.752974735=2024-06-26+21:07&entry.1917517419=2024-06-27+01:33&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by sarina** [comment]
Done!

**Pull request merged**
